name: kube-prometheus-stack
namespace: monitoring
syncWave: "2"
type: helm
# Embarque en plus les manifestes bruts de ./manifests (HTTPRoute) via une 3e source.
extraManifests: true
repoURL: https://prometheus-community.github.io/helm-charts
chart: kube-prometheus-stack
targetRevision: 87.10.1
