apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  parentRefs:
    - name: classlab
      namespace: kube-system
      sectionName: https
  hostnames:
    - alertmanager.classlab.lan
  rules:
    - backendRefs:
        - name: kube-prometheus-stack-alertmanager
          port: 9093
