# Manifeste ImageUpdater (nouveau modèle CRD) déployé en 3e source du composant helm.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - classlab-imageupdater.yaml
  - classlab-appset.yaml
  - java-demo-appweb-imageupdater.yaml
  - java-demo-appweb-appset.yaml
