# argocd-server tourne en mode insecure (patch bootstrap/argocd) : le Gateway
# termine le TLS, argocd sert du HTTP simple -> pas de boucle de redirection.
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: classlab
      namespace: kube-system
      sectionName: https
  hostnames:
    - argocd.classlab.lan
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: argocd-server
          port: 80
          weight: 1
